CREATE DATABASE IF NOT EXISTS `hope_bridge` DEFAULT CHARACTER SET latin1 COLLATE latin1_danish_ci;

DROP TABLE IF EXISTS `User`;

CREATE TABLE `User` (
    `id` INT  AUTO_INCREMENT PRIMARY KEY,
    'name' VARCHAR(255) NOT NULL,
    'email' VARCHAR(255) Unique,
    'password' VARCHAR(255)
);
