name: test_project

on:
  pull_request:
    branches:
      - developer

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: --health-cmd='mysqladmin ping --silent' --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Install Composer
      run: sudo apt-get update && sudo apt-get install -y composer

    - name: Install dependencies
      run: composer install

    - name: Set up .env file
      run: |
        cp .env.example .env
        echo "APP_KEY=$(php artisan key:generate --show)" >> .env
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=mysql" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=test_db" >> .env
        echo "DB_USERNAME=root" >> .env
        echo "DB_PASSWORD=root" >> .env

    - name: Run migrations
      run: php artisan migrate --force

    - name: Run seeders
      run: php artisan db:seed

    - name: Run tests
      run: php artisan test

    - name: Run code quality checks
      run: |
        composer run-script phpcs
        composer run-script phpmd
